services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: cars
    ports:
      - "5432:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data

  rest-api:
    build:
      context: ./rest-api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - rest-api/.env
    depends_on:
      - redis
      - postgres

  soap-api:
    build:
      context: ./soap-api
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - soap-api/.env
    volumes:
      - ./soap-api/database:/usr/src/app/database
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes: 
  postgres_data:


