# Usa una imagen base de Node.js
FROM node:14

# Establecer el directorio de trabajo
WORKDIR /usr/src/app

# Copiar el package.json y el package-lock.json
COPY package*.json ./

# Instalar las dependencias
RUN npm install

# Copiar el script de espera y darle permisos de ejecución 
COPY wait-for-postgres.sh . 
RUN chmod +x wait-for-postgres.sh

# Copiar el resto de los archivos de la aplicación
COPY . .

# Exponer el puerto en el que la aplicación va a correr
EXPOSE 4000

# Comando para correr la aplicación
CMD ["node", "src/index.js"]
