apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: lhr-api
type: Opaque
data:
  DB_HOST: cG9zdGdyZXM=          
  DB_USER: YWRtaW4=              
  DB_PASSWORD: dG9vcg==          
  DB_NAME: Y2Fycw==              
  DB_PORT: NTQzMg==              
  SOAP_URL: aHR0cDovL2xvY2FsaG9zdDo1MDAxL3NvYXA/d3NkbA==   # http://localhost:5001/soap?wsdl en base64
