apiVersion: v1
kind: Service
metadata:
  name: rest-api
  namespace: lhr-api
spec:
  type: NodePort
  selector:
    app: rest-api
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
    nodePort: 30080  # Puedes ajustar este puerto si es necesario
