# Usa una imagen base de Node.js
FROM node:14

# Establecer el directorio de trabajo
WORKDIR /usr/src/app

# Copiar el package.json y el package-lock.json
COPY package*.json ./

# Instalar las dependencias
RUN npm install

# Recompilar dependencias nativas 
RUN npm rebuild sqlite3

# Crear carpeta para la base de datos
RUN mkdir -p /usr/src/app/database

# Copiar el resto de los archivos de la aplicación
COPY . .

# Exponer el puerto en el que la aplicación va a correr
EXPOSE 5001

# Comando para correr la aplicación
CMD ["node", "src/index.js"]
